#!/usr/bin/env bash
# Change IPs for localhost and facebook.com
cp /etc/hosts ~/hosts.new
printf "127.0.0.2\tlocalhost\n" > ~/hosts.new
printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
