#!/usr/bin/env bash
# Change IPs for localhost and facebook.com
cp /etc/hosts ~/hosts.new
echo "127.0.0.2\tlocalhost" > ~/hosts.new
echo "8.8.8.8.\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
